export const FETCH_EVENT_LIST_INITIATED = 'FETCH_EVENT_LIST_INITIATED';
export const FETCH_EVENT_LIST_SUCCESS = 'FETCH_EVENT_LIST_SUCCESS';
export const FETCH_EVENT_LIST_FAIL = 'FETCH_EVENT_LIST_FAIL';

export const FETCH_EVENT_INITIATED = 'FETCH_EVENT_INITIATED';
export const FETCH_EVENT_SUCCESS = 'FETCH_EVENT_SUCCESS';
export const FETCH_EVENT_FAIL = 'FETCH_EVENT_FAIL';

export const CREATE_EVENT_INITIATED = 'CREATE_EVENT_INITIATED';
export const UPDATE_EVENT_INITIATED = 'UPDATE_EVENT_INITIATED';
export const UPDATE_EVENT_SUCCESS = 'UPDATE_EVENT_SUCCESS';
export const UPDATE_EVENT_FAIL = 'UPDATE_EVENT_FAIL';
